### PR TITLE
I just improvised it, added new things, and some new links :D

### PR DESCRIPTION
**Pull request by RISHAB-CREATOR**
1) SCROLL BAR IS UPDATED
2) LOADING BAR IS ADDED
3) ANTI DEV TOOLS SYSTEM HAS BEEN ADDED
4) SECURITY IMPROVISED
5) ADDED A CUSTOM 404 PAGE
6) ADDED A PWA
7) ADDED ROBOTS.TXT FOR BETTER SEO AND TO PREVENT SITE CLONERS
8) ADDED RESIZED ICONS
9) ADDED A dmca.html KINDLY EDIT THE MAIL THERE
10) ADDED SMOOTH SCROLLING
11) TORRENT SECTION

### CODE REVIEW

**Comment by RISHAB-CREATOR** [comment]
@N3rdmade Review the changes from this deploy : https://rishab-creator.github.io/TBCPL/

**Comment by N3rdmade** [comment]
Interesting changes however i was mostly looking to not use JS so that people would trust the site more as it develops. (reddit seems to be scared of site with it lol) The dmca is a good idea. The scroll bar looks a lot cleaner as well thats great. Im assuming the Rgshows is your site?

**Comment by RISHAB-CREATOR** [comment]
Yes rgshows is my site,
And there are only 3 js used around the whole fork of mine

**Comment by N3rdmade** [comment]
> Yes rgshows is my site, And there are only 3 js used around the whole fork of mine

I dont mind using them they are commonly used, I changed up the scroll bar my own way but did take your idea of making it slimmer and darker and did add that guys smooth scrolling Js and i did add a Dmca button at the bottom as well. 

I did not apply the MIT license just yet I'm not happy with its wording. 

and i may add rgshows in the future however i want to test it out more it seems there is very little so far under your live tv section and im not finding some movies and anime. looks great though.

**Pull request closed without merging**
